#ifndef CONFIG_H
#define CONFIG_H

#define LED_GREEN 2
#define LED_RED 3
#define LED_IR 13
#define BUTTON_SIGNALS 5
#define LED_BLUE 6
#define IR_RECV 10
#define DEFAULT_LED_SIGNAL_DURATION 1
#define DEFAULT_BAUD_RATE 9600
#define RECV_SINGALS_BUFFER_SIZE 230
// #define TOTAL_SIGNAL_STORED 2
#define ACCEPT_RAW_SIGNAL_MIN_LENGTH 50
#define DEFAULT_LONG_PRESS_DURATION 2
#define FREQ 38
#define BUFFER_DEFALUT_VALUE 0

#endif
